# Generated by Django 4.1.1 on 2022-10-10 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("eprofile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="lessons_learned",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="words_learned",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="userprofilepicture",
            name="user_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_profile_picture",
                to="eprofile.userprofile",
            ),
        ),
    ]
